num1 = int(input("Entra un numero: "))
num2 = int(input("Entra un numero: "))
num3 = int(input("Entra un numero: "))
num4 = int(input("Entra un numero: "))
num5 = int(input("Entra un numero: "))
num6 = int(input("Entra un numero: "))
num7 = int(input("Entra un numero: "))
num8 = int(input("Entra un numero: "))
num9 = int(input("Entra un numero: "))
num10 = int(input("Entra un numero: "))

laTuplaOriginal = (num1,num2,num3,num4,num5,num6,num7,num8,num9,num10)
laTuplaOrdenada = tuple(sorted(laTuplaOriginal))
print(laTuplaOrdenada)